---
# User and group management
- name: Ensure group for this play app exists
  group:
    name: "{{ play_application_group }}"
    state: present

- name: Ensure user for this play app exists
  user:
    name: "{{ play_application_username }}"
    groups: "{{ play_application_group }}"
    createhome: no
    shell: /bin/bash
    system: yes
    state: present

# File system structure
- name: Ensure project directory exists
  file:
    path: "{{ play_application_path }}"
    state: directory
    recurse: yes
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"

# Application installation
- name: Install supporting software
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - unzip

- name: Download application universal package
  get_url:
    url: "{{ play_application_url }}"
    dest: /tmp/
  register: play_application_download

- name: Ensure application exists within the play app file system
  unarchive:
    copy: no
    src: "{{ play_application_download.dest }}"
    dest: "{{ play_application_path }}/"
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"
  become: yes
  become_user: "{{ play_application_username }}"

- name: Ensure link is pointing to latest version
  file:
    src: "{{ play_application_path }}/{{ play_application_name }}-{{ play_application_version }}"
    dest: "{{ play_application_path }}/current"
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"
    state: link

#  Application modification
- name: Create central log directory
  file:
    path: "/var/log/{{ play_application_group }}/{{ play_application_username }}"
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"
    state: directory
    recurse: yes

- name: Link application log directory to central directory
  file:
    src: "/var/log/{{ play_application_group }}/{{ play_application_username }}"
    dest: "{{ play_application_path }}/current/logs"
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"
    state: link

- name: Ensure correct values are used within configuration file.
  lineinfile:
    dest: "{{ play_application_path }}/current/conf/application.conf"
    group: "{{ play_application_group }}"
    line: "{{ item.key }}=\"{{ item.value }}\""
    owner: "{{ play_application_username }}"
    regexp: "(#|){{ item.key }}=.*"
    state: present
  with_items: "{{ play_application_overrides|default([]) }}"

# Service installation
- name: Ensure the upstart configuration exists on the system
  template:
    src: upstart.j2
    dest: "/etc/init/{{ play_application_name }}.conf"
  sudo: yes
  notify:
    - restart service
