---
# User and group management
- name: Ensure group for this play app exists
  group:
    name: "{{ play_application_group }}"
    state: present

- name: Ensure user for this play app exists
  user:
    name: "{{ play_application_username }}"
    groups: "{{ play_application_group }}"
    createhome: no
    shell: /bin/bash
    system: yes
    state: present

# File system structure
- name: Ensure project directory exists
  file:
    path: "{{ play_application_path }}"
    state: directory
    recurse: yes
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"

# Application installation
- name: Install supporting software
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - unzip

- name: create temporary download directory
  tempfile:
    state: directory
    suffix: play
  register: dms_editor_download_dir

- name: ensure archive exists from url
  get_url:
    url: "{{ play_application_url }}"
    dest: "{{ dms_editor_download_dir.path }}/"
  when: not(
      (play_application_url is undefined) or
      (play_application_url is none) or
      (play_application_url|trim == '')
    )

- name: ensure archive exists from s3/minio
  aws_s3:
    aws_access_key: "{{ play_minio_access_key }}"
    aws_secret_key: "{{ play_minio_secret_key }}"
    bucket: distribution
    dest: "{{ dms_editor_download_dir.path }}/{{ play_application_filename }}"
    mode: get
    object: "jenkins/dms/play-scala/{{ play_application_filename }}"
    rgw: True
    s3_url: https://minio.newedgeengineering.net/
  when: not(
      (play_minio_access_key is undefined) or
      (play_minio_access_key is none) or
      (play_minio_access_key|trim == '')
    ) and not(
      (play_minio_secret_key is undefined) or
      (play_minio_secret_key is none) or
      (play_minio_secret_key|trim == '')
    )

- name: Ensure application exists within the play app file system
  unarchive:
    src: "{{ dms_editor_download_dir.path }}/{{ play_application_filename }}"
    dest: "{{ play_application_path }}"
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"
    remote_src: yes

- name: Ensure application has the correct permissions
  file:
    dest: "{{ play_application_path }}"
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"
    recurse: yes
    state: directory

- name: Ensure link is pointing to latest version
  file:
    src: "{{ play_application_path }}/{{ play_application_name }}-{{ play_application_version }}"
    dest: "{{ play_application_path }}/current"
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"
    state: link

#  Application modification
- name: Create central log directory
  file:
    path: "/var/log/{{ play_application_group }}/{{ play_application_username }}"
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"
    state: directory
    recurse: yes

- name: Link application log directory to central directory
  file:
    src: "/var/log/{{ play_application_group }}/{{ play_application_username }}"
    dest: "{{ play_application_path }}/current/logs"
    owner: "{{ play_application_username }}"
    group: "{{ play_application_group }}"
    state: link

# - debug: msg="boolean?  {{ item.value is sameas False or item.value is sameas True }}"
#   with_items: "{{ play_application_overrides|default([]) }}"
# - debug: msg="string?  {{ not(item.value is sameas False or item.value is sameas True) and not(item.value is number) }}"
#   with_items: "{{ play_application_overrides|default([]) }}"
# - debug: msg="number?  {{ not(item.value is sameas False or item.value is sameas True) and item.value is number }}"
#   with_items: "{{ play_application_overrides|default([]) }}"

- name: Ensure correct string values are used within configuration file.
  lineinfile:
    dest: "{{ play_application_path }}/current/conf/application.conf"
    group: "{{ play_application_group }}"
    line: "{{ item.key }}=\"{{ item.value }}\""
    owner: "{{ play_application_username }}"
    regexp: "^(#|){{ item.key }}=(\").*(\"|)$"
    state: present
  when: not(item.value is sameas False or item.value is sameas True) and not(item.value is number)
  with_items: "{{ play_application_overrides|default([]) }}"

- name: Ensure correct number values are used within configuration file.
  lineinfile:
    dest: "{{ play_application_path }}/current/conf/application.conf"
    group: "{{ play_application_group }}"
    line: "{{ item.key }}={{ item.value }}"
    owner: "{{ play_application_username }}"
    regexp: "^(#|){{ item.key }}=[0-9]{0,}$"
    state: present
  when: not(item.value is sameas False or item.value is sameas True) and item.value is number
  with_items: "{{ play_application_overrides|default([]) }}"

- name: Ensure correct boolean values are used within configuration file.
  lineinfile:
    dest: "{{ play_application_path }}/current/conf/application.conf"
    group: "{{ play_application_group }}"
    line: "{{ item.key }}={{ item.value|lower }}"
    owner: "{{ play_application_username }}"
    regexp: "^(#|){{ item.key }}=(true|false)$"
    state: present
  when: item.value is sameas False or item.value is sameas True
  with_items: "{{ play_application_overrides|default([]) }}"

# Service installation
- name: Ensure the upstart configuration exists on the system
  template:
    src: upstart.j2
    dest: "/etc/init/{{ play_application_name }}.conf"
  when: lookup('env', 'ANSIBLE_CONTAINER') is not defined
  notify:
    - restart service
